---
title: "Tarea 7. Pregunta 11.1"
---

---------------------------------------------------------------------------------
1) Pruebe que $\mathscr{B}(\mathbb{R})\otimes\mathscr{B}(\mathbb{R}) = \mathscr{B}(\mathbb{R}^2)$, 

Demostración:

Demostraremos la igualdad mostrando que las contenciones.

1.1 PD. $\mathscr{B}(\mathbb{R}^2) \subseteq \mathscr{B}(\mathbb{R})\otimes\mathscr{B}(\mathbb{R})$.

Sean $a,b,c,d \in \mathbb{R}$ tales que $(a,b) \times (c,d)$ formen algun rectángulo (arbitrario) en $\mathbb{R}^2$.

Así 

  (a) $(a,b) \times (c,d) \in \mathscr{B}(\mathbb{R})\otimes\mathscr{B}(\mathbb{R})$ pues $(a,b), (c,d) \in \mathscr{B}(\mathbb{R})$.
  
  (b)$(a,b) \times (c,d) \in \mathscr{B}(\mathbb{R}^2)$ pues $\mathscr{B}(\mathbb{R}^2)$ es generada por los rectangulos de $\mathbb{R}^2$.

Pero $\mathscr{B}(\mathbb{R}^2)$ es la mínima que contiene a todos los rectangulos, por lo que:


\[\mathscr{B}(\mathbb{R}^2) \subseteq \mathscr{B}(\mathbb{R})\otimes\mathscr{B}(\mathbb{R})\]


1.2 PD. $\mathscr{B}(\mathbb{R})\otimes\mathscr{B}(\mathbb{R}) \subseteq \mathscr{B}(\mathbb{R}^2)$.

Sea \[S_{I} = \{A \subseteq \mathbb{R} | A \times \mathbb{R} \in \mathscr{B}(\mathbb{R}^2)\}.\]
(La $I$ es porque varia el termino de la izquierda).


Mostraremos que es una $\sigma$-álgebra.


(a) $\mathbb{R} \in S$ ya que $\mathbb{R} \times \mathbb{R} \in \mathscr{B}(\mathbb{R}^2)\}$.


(b) Si $A \in S$ entonces $A^c \in S$.

Sea $A \in S$.
\[A^c \times \mathbb{R} = (A \times \mathbb{R})^c \in  \mathscr{B}(\mathbb{R}^2) \quad \mbox{(pues } \mathscr{B}(\mathbb{R}^2) \mbox{ es } \sigma-\mbox{álgebra)}\]
\[\therefore A^c \in S\]


(c) Sean $(A_n)_{n \in \mathbb{N}} \in S$ entonces $\cup_{n \in \mathbb{N}} A_n \in S$.

\[(\cup_{n \in \mathbb{N}} A_n) \times \mathbb{R} = \cup_{n \in \mathbb{N}} (A_n \times \mathbb{R}) \in  \mathscr{B}(\mathbb{R}^2) \quad \mbox{(pues } \mathscr{B}(\mathbb{R}^2) \mbox{ es } \sigma-\mbox{álgebra)}\]


De (a), (b) y (c) concluimos que $S$ es $\sigma$-álgebra.


Es fácil ver que los intervalos $(a,b) \in S$. Por lo que $\mathscr{B}(\mathbb{R}) \subseteq S$.


Si definimos $S_D = \{B \in \mathscr{B}(\mathbb{R})| \mathbb{R} \times B \in \mathscr{B}(\mathbb{R}^2)\}$ podemos mostrar que es una $\sigma$-álgebra.


Luego, para cualquier par $A,B \in  \mathscr{B}(\mathbb{R})$ se cumple que

\[A\times B = (A \times \mathbb{R}) \cap (\mathbb{R} \times B) \in  \mathscr{B}(\mathbb{R}^2)\]

Por lo que

\[\mathscr{B}(\mathbb{R})\otimes\mathscr{B}(\mathbb{R}) \subseteq \mathscr{B}(\mathbb{R}^2)\]


De ambos casos se concluye que


\[\mathscr{B}(\mathbb{R})\otimes\mathscr{B}(\mathbb{R}) = \mathscr{B}(\mathbb{R}^2)\]


---------------------------------------------------------------------------------
2) ¿Se cumple para $n,m \in\mathbb{N}$?


Sí, si se cumple. (Es análogo)


Sean $a_i,b_i \in \mathbb{R}$ para $i = 1, \dots, m+n$ tales que $(a_1,b_1) \times (a_2,b_2) \times \dots \times (a_{n+m},b_{n+m})$ formen algún hiperectangulo (arbitrario) en $\mathbb{R}^{n+m}$.

Así 

  (a) $\prod_{i=1}^{n+m}  (a_i,b_i) \in \mathscr{B}(\mathbb{R}^n)\otimes\mathscr{B}(\mathbb{R}^m)$ pues $\prod_{i=1}^{n}(a_i,b_i) \in \mathscr{B}(\mathbb{R}^n)$ y $\prod_{i=n+1}^{n+m} (a_i,b_i) \in \mathscr{B}(\mathbb{R}^{m+n})$.
  
  (b)$\prod_{i=1}^{n+m}  (a_i,b_i) \in \mathscr{B}(\mathbb{R}^{n+m})$ pues $\mathscr{B}(\mathbb{R}^{n+m})$ es generada por los rectangulos de $\mathbb{R}^{n+m}$.

Pero $\mathbb{R}^{n+m}$ es la mínima que contiene a todos los rectangulos, por lo que:


\[\mathscr{B}(\mathbb{R}^{n+m}) \subseteq \mathscr{B}(\mathbb{R}^{n})\otimes\mathscr{B}(\mathbb{R}^{m})\]

1.2 PD. $\mathscr{B}(\mathbb{R}^n)\otimes\mathscr{B}(\mathbb{R}^m) \subseteq \mathscr{B}(\mathbb{R}^{n+m})$.

Sea \[S_{I} = \{A \subseteq \mathbb{R}^n | A \times \mathbb{R}^m \in \mathscr{B}(\mathbb{R}^{n+m})\}.\]
(La $I$ es porque varia el termino de la izquierda).


Mostraremos que es una $\sigma$-álgebra.


(a) $\mathbb{R}^n \in S$ ya que $\mathbb{R}^n \times \mathbb{R}^m \in \mathscr{B}(\mathbb{R}^{n+m})\}$.


(b) Si $A \in S$ entonces $A^c \in S$.

Sea $A \in S$.
\[A^c \times \mathbb{R}^m = (A \times \mathbb{R}^m)^c \in  \mathscr{B}(\mathbb{R}^{n+m}) \quad \mbox{(pues } \mathscr{B}(\mathbb{R}^{n+m}) \mbox{ es } \sigma-\mbox{álgebra)}\]
\[\therefore A^c \in S\]


(c) Sean $(A_n)_{n \in \mathbb{N}} \in S$ entonces $\cup_{n \in \mathbb{N}} A_n \in S$.

\[(\cup_{n \in \mathbb{N}} A_n) \times \mathbb{R}^m = \cup_{n \in \mathbb{N}} (A_n \times \mathbb{R}^m) \in  \mathscr{B}(\mathbb{R}^{n+m}) \quad \mbox{(pues } \mathscr{B}(\mathbb{R}^{n+m}) \mbox{ es } \sigma-\mbox{álgebra)}\]


De (a), (b) y (c) concluimos que $S$ es $\sigma$-álgebra.


Es fácil ver que los intervalos $(a,b) \in S$. Por lo que $\mathscr{B}(\mathbb{R}) \subseteq S$.


Si definimos $S_D = \{B \in \mathscr{B}(\mathbb{R}^m)| \mathbb{R}^n \times B \in \mathscr{B}(\mathbb{R}^{n+m})\}$ podemos mostrar que es una $\sigma$-álgebra.


Luego, para cualquier $A \in \mathscr{B}(\mathbb{R}^n)$ y $B \in \mathscr{B}(\mathbb{R}^m)$ se cumple que


\[A\times B = (A \times \mathbb{R}^m) \cap (\mathbb{R}^n \times B) \in  \mathscr{B}(\mathbb{R}^{n+m})\]

Por lo que

\[\mathscr{B}(\mathbb{R}^n)\otimes\mathscr{B}(\mathbb{R}^m) \subseteq \mathscr{B}(\mathbb{R}^{n+m})\]


De ambos casos se concluye que


\[\mathscr{B}(\mathbb{R}^n)\otimes\mathscr{B}(\mathbb{R}^m) = \mathscr{B}(\mathbb{R}^{n+m}).\]

