---
title: "Tarea 8. Pregunta 14.1."
---

### Sea $(\Omega, \mathscr{A}, \mathbb{P})$ un espacio de probabilidad y $(X_n)_{n \in \mathbb{N}}$ una sucesion de v.a. definidas de $(\Omega, \mathscr{A}, \mathbb{P})$. Sea $A_n(\epsilon) =\{\omega \in \Omega : |X_n(\omega) - X(\omega)| \geq \epsilon \}$. Pruebe que:


-----------------------------------------------------------------------------
(A). $X_n \overset{c.s.}{\to} X$ si y sólo para todo $\epsilon > 0$ se cumple $\mathbb{P}[\lim \sup_n A_n(\epsilon)] = 0$.
-----------------------------------------------------------------------------

Demostración:

Reescribamos la hipótesis $X_n \overset{c.s.}{\to} X$:
\[
\begin{align*}
1 &= \mathbb{P}(\{\omega \in \Omega| \lim_{n \to \infty} X_n(\omega) = X(\omega)\})&& \mbox{(Definición de c.s.)}\\\\
&= \mathbb{P}(\{\omega \in \Omega| \forall m \in \mathbb{N} \mbox{ } \exists N \in \mathbb{N} \mbox{ tal que } n \geq N \implies |X_n(\omega) - X(\omega)| < \frac{1}{m} \})&& \mbox{(Equivalencia de lim)}\\\\
&= \mathbb{P}(\{\omega \in \Omega| \forall m \in \mathbb{N} \mbox{ } \exists N \in \mathbb{N} \mbox{ tal que } n \geq N \implies \omega \in A_n^c(\frac{1}{m}) \}) && \mbox{(Def. de } A_{n}(\epsilon))\\\\
&= \mathbb{P}(\{\omega \in \Omega| \forall m \in \mathbb{N} \mbox{ } \exists N \in \mathbb{N} \mbox{ tal que } \omega \in \cap_{n = N}^\infty A_n^c(\frac{1}{m}) \})&& \mbox{(Def. de } \cap_{i = i_0}^\infty)\\\\ 
&= \mathbb{P}(\{\omega \in \Omega| \forall m \in \mathbb{N} \mbox{ tal que } \omega \in \cup_{N = 1}^\infty \cap_{n = N}^\infty A_n^c(\frac{1}{m}) \})&& \mbox{(Def. de } \cup_{i = i_0}^\infty)\\\\
&= \mathbb{P}(\{\omega \in \Omega|\forall m \in \mathbb{N} \quad \omega \in \lim \inf_n A_n^c(\frac{1}{m}) \})&& \mbox{(Definición de lim inf)}\\\\
&= \mathbb{P}(\{\omega \in \Omega|\omega \in \cap_{m =1}^\infty \lim \inf_n A_n^c(\frac{1}{m}) \})&& \mbox{(Def. de } \cup_{i = i_0}^\infty)\\\\
&= \mathbb{P}(\{\omega \in \Omega|\omega \in [\cup_{m =1}^\infty \lim \sup_n A_n(\frac{1}{m})]^c \})&& \mbox{(Leyes de DMorgan)}
\end{align*}
\]
 
Por lo tanto $X_n \overset{c.s.}{\to} X$ es equivalente a decir que

\[\mathbb{P}[\cup_{m =1}^\infty \lim \sup_n A_n(\frac{1}{m})] = 0.\]

Ahora demostraremos la implicación.


($\implies$) Supongase que $X_n \overset{c.s.}{\to} X$. PD. $\forall \epsilon>0 \quad \mathbb{P}[\lim \sup_n A_n(\epsilon)] = 0$.

Hagamos primero dos observaciones:

(1) Notese que $(A_n(\epsilon))_{\epsilon>0}$ es decreciente (respecto de $\epsilon$). Sea $\epsilon_1 < \epsilon_2$ entonces:

\[
\begin{align*}
A_n(\epsilon_2) &= \{\omega \in \Omega | |X_n(\omega)-X(\omega)| \geq \epsilon_2 > \epsilon_1\}\\\\
&\subseteq \{\omega \in \Omega | |X_n(\omega)-X(\omega)| \geq \epsilon_1\}\\\\
&= A_n(\epsilon_1)\\\\
&\therefore A_n(\epsilon_2) \subseteq A_n(\epsilon_1)
\end{align*}
\]

(2) Sabemos que $\mathbb{P}[\lim \sup_n A_n(\frac{1}{m})] \subseteq \mathbb{P}[\cup_{m =1}^\infty \lim \sup_n A_n(\frac{1}{m})] \overset{hipótesis}{=} 0$.
\[\therefore  \forall m \in \mathbb{N} \quad \mathbb{P}[\lim \sup_n A_n(\frac{1}{m})] = 0\]

Ahora hagamos la demostración. 

Sea $\epsilon >0$.

Así, por $(1)$ y por la propiedad arquimediana

\[\exists m_0 \in \mathbb{N} \quad \mbox{tal que } \mathbb{P}[\lim \sup_n A_n(\epsilon)] \leq \mathbb{P}[\lim \sup_n A_n(\frac{1}{m_0})]\]


Y por $(2)$

\[\mathbb{P}[\lim \sup_n A_n(\epsilon)] = 0\]

\[\therefore \forall \epsilon>0 \quad \mathbb{P}[\lim \sup_n A_n(\epsilon)] = 0.\]

($\Longleftarrow$) Supongase que $\forall \epsilon>0 \quad \mathbb{P}[\lim \sup_n A_n(\epsilon)] = 0$. PD. $X_n \overset{c.s.}{\to} X$.

\[\mbox{PD. } \mathbb{P}[\cup_{m =1}^\infty \lim \sup_n A_n(\frac{1}{m})] = 0.\] 

\[
\mathbb{P}[\cup_{m =1}^\infty \lim \sup_n A_n(\frac{1}{m})] \leq \sum_m^\infty  \mathbb{P}[\lim \sup_n A_n(\frac{1}{m})] \overset{hipótesis}{=} 0.
\]

-----------------------------------------------------------------------------
(B). Si para cada $\epsilon >0$ la serie $\sum_n \mathbb{P}[A(\epsilon)]$ converge entonces $X_n \overset{c.s.}{\to} X$.
-----------------------------------------------------------------------------

Demostración:

Recordemos el lema de Borel-Cantelli (parte 1): Sea $\{B_n:n\in \mathbb{N}\}$ una sucesión de eventos, y defina $B = \lim \sup_n B_n$ entonces si $\sum_{n=1}^\infty \mathbb{P}(B_n) < \infty \implies P(B) = 0$.


Sabemos que $\sum_n \mathbb{P}[A_n(\epsilon)]$ converge $\forall \epsilon>0$.
Entonces 

\[\mathbb{P}[\lim \sup_n A_n(\epsilon)] = 0 \quad \forall \epsilon>0\]

Luego por (A) concluimos que $X_n \overset{c.s.}{\to} X$.

-----------------------------------------------------------------------------
(C). Si para cada $\epsilon > 0$ los eventos $A_n = \{|X_n - X| \geq \epsilon\}$, $n \in \mathbb{N}$ son independientes, es cierto que $X_n \overset{c.s.}{\to} X$ si y sólo si la serie $\sum_n \mathbb{P}[|X_n-X|\geq\epsilon]$ es convergente.
-----------------------------------------------------------------------------

Demostración:

Sean $A_n = \{|X_n - X| \geq \epsilon\}$ eventos independientes para toda $\epsilon >0$ y toda $n \in \mathbb{N}$.

Recordemos el lema de Borel-Canteli (parte 2): Si $B_1, B_2, \dots$ son independientes y $\sum_n \mathbb{P}(B_n) = \infty$ entonces $\mathbb{P}(\lim \sup_n B_n) = 1$.

($\implies$) Supongase que $X_n \overset{c.s.}{\to} X$. P.D.$\forall \epsilon >0 \quad \sum_n \mathbb{P}[|X_n-X|\geq\epsilon]$ es convergente.

Por (A) sabemos que:
\[\mathbb{P}(\lim \sup_n A_n(\epsilon)) = 0 \quad \forall \epsilon>0\]

Entonces por la contrapuesta de la segunda parte del lema de Borel-Canterli tenemos que 

\[\forall \epsilon >0 \quad \sum_n \mathbb{P}[|X_n-X|\geq\epsilon]<\infty\]

($\Longleftarrow$)
Demostración: Inciso (B).


