---
title: "Tarea 9. Pregunta 15.2."
---

### Sea $X$ una v.a. definida en $(\Omega, \mathscr{A}, \mathbb{P})$ y $q>0$. Si $\mathbb{E}|X|^q < \infty$, entonces $\lim_{x \to \infty} x^q\mathbb{P}(|X|\geq x) = 0$.

Demostración:

Sea $(a_n)_{n \in \mathbb{N}}$ una sucesión creciente tal que $\lim_{n \to \infty} a_n = \infty$.

Sea \[Y_n= |X|^q 1_{\{|X|>a_n\}}.\]

Definamos \[A_n(\epsilon) = \{\omega \in \Omega: |Y_n(\omega)-0|\geq\epsilon\}.\]

De acuerdo con el razonamiento escrito en **[Pregunta 14.1.](https://austriamax.github.io/austriamax.probaP.github.io/P14_1.html)** tenemos que:

\[Y_n \overset{c.s.}{\to} 0 \iff \mathbb{P}[\cup_{m =1}^\infty \lim \sup_n A_n(\frac{1}{m})] = 0.\]

Calcularemos $\mathbb{P}[\lim \sup_n A_n(\frac{1}{m})]$ para alguna $m \in \mathbb{N}$:

Notemos que $\{A_n(\frac{1}{m})\}_{n \in \mathbb{N}}$ es una sucesión decreciente pues (respecto a $n$):

Sea $n_1 < n_2 \implies a_{n_1} < a_{n_2} \implies $

\begin{align*}
n < m &\implies a_{n} < a_{m} && (a_n\mbox{ es creciente})\\\\
&\implies \{\omega \in \Omega:|X(\omega)|>a_n\} \supseteq \{\omega \in \Omega:|X(\omega)|>a_m\}\\\\
& \implies 1_{\{\omega \in \Omega:|X(\omega)|>a_n\}} \geq 1_{\{\omega \in \Omega:|X(\omega)|>a_m\}}\\\\
&\implies \{\omega \in \Omega : |X(\omega)|^q 1_{\{\omega \in \Omega:|X(\omega)|>a_n\}} \geq \epsilon\} \supseteq \{\omega \in \Omega: |X(\omega)|^q1_{\{\omega \in \Omega:|X(\omega)|>a_m\}} \geq \epsilon\}\\\\
&\implies A_n(\epsilon) \supseteq A_m(\epsilon).
\end{align*}\]

Entonces:

\[\begin{align*}
\mathbb{P}[\lim \sup_n A_n(\frac{1}{m})] &= \mathbb{P}[\cap_{n=1}^\infty A_n(\frac{1}{m})]\\\\
&= \mathbb{P}[\{\omega \in \Omega : |X(\omega)|^q 1_{\{\omega \in \mathbb{N}:|X(\omega)|>\infty\}}\geq \frac{1}{m}\}] && (\lim_{n \to \infty} a_n = \infty)\\\\
&=0.
\end{align*}\]

Por lo tanto:
\[\therefore Y_n \overset{c.s.}{\to} 0.\]

Por definición
\[Y_n > a_n1_{\{\omega \in \Omega:|X(\omega)|>a_n\}}\]
entonces
\[\mathbb{E}[Y_n] \geq a_n\mathbb{P}[{\{\omega \in \Omega:|X(\omega)|>a_n\}}]\]

Además 
\[|Y_n| < |X|^q \quad (\mbox{Con} X\in \mathscr{L}^p)\]

Entonces por el teorema de la convergencia dominada $\lim_{n \to \infty} \mathbb{E}(Y_n) = 0$.

Tomando $a_n = n = x$

\[\therefore \lim_{x \to \infty} x^q\mathbb{P}(|X|\geq x) = 0\]

