---
title: "Tarea 10. Pregunta 16.9."
---


### Si $X \sim N(0,1)$. Pruebe que:

--------------------------------------------------------------------------------
(a) \[\mathbb{E}[X^{2n+1}] = 0 \quad \mbox{y} \quad \mathbb{E}[X^{2n}] = \frac{(2n)!}{2^nn!}.\]
--------------------------------------------------------------------------------


Demostración:

\[\begin{align*}
\mathbb{E}[X^k] &= \frac{1}{\sqrt{2\pi}}\int_{-\infty}^\infty x^k e^{-\frac{x^2}{2}}dx\\\\
&= \frac{1}{\sqrt{2\pi}}\int_{-\infty}^0 x^k e^{-\frac{x^2}{2}}dx + \frac{1}{\sqrt{2\pi}}\int_{0}^\infty x^k e^{-\frac{x^2}{2}}dx\\\\
&=A +B
\end{align*}\]


Haciendo el cambio de variable $Y = -X$ podemos ver que $A = (-1)^kB$, con lo cual

\[\begin{align*}
\mathbb{E}[X^k] &= [1+(-1)^k]B\\\\
&= [1 + (-1)^k]\frac{1}{\sqrt{2\pi}}\int_0^\infty x^ke^{-\frac{x^2}{2}}dx\\\\
\end{align*}\]

Pero viendo el cambio de variable
\[y = \frac{x^2}{2} \to x = \sqrt{2y} \to dx = \frac{dy}{\sqrt{2y}}\]

\[\mathbb{E}[X^k] = \frac{[1+(-1)^k]2^{\frac{k}{2}-1}}{\sqrt{\pi}}\int_0^\infty y^{\frac{k+1}{2}-1}e^{-y}dy = \frac{[1+(-1)^k]2^{\frac{k}{2}-1}}{\sqrt{\pi}} \Gamma(\frac{k+1}{2})\]

Por lo tanto

\[\mathbb{E}[X^k] = \frac{[1+(-1)^k]2^{\frac{k}{2}-1}}{\sqrt{\pi}} \Gamma(\frac{k+1}{2})\]

Es claro que cuando $k$ es impar $\mathbb{E}[X^k] = 0$ (por el $(-1)^k$).

\[\therefore \mathbb{E}[X^{2n+1}] = 0.\]

Cuando $k$ es par nos podemos apoyar de la siguiente relación (aún que no es necesario que $k$ sea par para usarla):

\[\Gamma(\frac{1}{2}+n) = \frac{(2n)!}{4^nn!}\sqrt{\pi} = \frac{(2n-1)!!}{2^n}\sqrt{\pi} = {n -\frac{1}{2}\choose n}n!\sqrt{\pi}.\]

Que se encuentra disponible en **[aquí](http://oeis.org/A001147)** ó **[aquí.](http://oeis.org/A000079)**

Así 
\[\begin{align*}
\mathbb{E}[X^{2n}] &= \frac{[1+(-1)^{2n}]2^{\frac{{2n}}{2}-1}}{\sqrt{\pi}}\frac{(2n)!}{4^nn!}\sqrt{\pi}\\\\
&= \frac{(2n)!}{2^{n}n!}
\end{align*}\]

Por lo tanto 
\[\therefore \mathbb{E}[X^{2n}] = \frac{(2n)!}{2^{n}n!}.\]


--------------------------------------------------------------------------------
(b) Encuentre la transformada de Laplace de $X$, $\mathbb{E}[e^{\lambda X}]$ con $\lambda \in \mathbb{R}$ y su función generadora de momentos $M_X(s) = \mathbb{E}[s^X]$.
--------------------------------------------------------------------------------


(Transformada de Laplace)

Calculemos la tranformada $F(z)$ con $z \in \mathbb{C}$.

\[\begin{align*}
F(z) &= \int_0^\infty\frac{1}{\sqrt{2\pi \sigma^2}}\exp[-\frac{(t - \mu)^2}{2\sigma^2}]\exp[-zt]dt\\\\
&= \int_0^\infty\frac{1}{\sqrt{2\pi \sigma^2}}\exp[-\frac{(t - \mu)^2}{2\sigma^2}-zt]dt\\\\
&= \int_0^\infty\frac{1}{\sqrt{2\pi \sigma^2}}\exp[-\frac{(t - \mu)^2-2\sigma^2zt}{2\sigma^2}]dt\\\\
&= \int_0^\infty\frac{1}{\sqrt{2\pi \sigma^2}}\exp[-\frac{t^2 -2( \mu-\sigma^2z)t + \mu^2}{2\sigma^2}]dt\\\\
&= \int_0^\infty\frac{1}{\sqrt{2\pi \sigma^2}}\exp[-\frac{(t-\mu+\sigma^2z)^2 -( \mu+\sigma^2z)^2+ \mu^2}{2\sigma^2}]dt\\\\
&= \exp[-\frac{(\mu+\sigma^2z)^2- \mu^2}{2\sigma^2}]\int_0^\infty\frac{1}{\sqrt{2\pi \sigma^2}}\exp[-\frac{(t-\mu-\sigma^2z)^2}{2\sigma^2}]dt\\\\
\end{align*}\]

Proponiendo el cambio de variable

\[Y = \frac{t-\mu-\sigma^2z}{\sigma}\]

Entonces 

\[\begin{align*}
F(z) &= \exp[-\frac{(\mu+\sigma^2z)^2- \mu^2}{2\sigma^2}]\int_{\frac{-\mu -\sigma^2z}{\sigma}}^\infty\frac{1}{\sqrt{2\pi}}\exp[-\frac{y^2}{2}]dy
\\\\
&= \exp[-\frac{(\mu+\sigma^2z)^2- \mu^2}{2\sigma^2}][1-\int_{-\infty}^{\frac{-\mu -\sigma^2z}{\sigma}}\frac{1}{\sqrt{2\pi}}\exp[-\frac{y^2}{2}]dy]
\end{align*}\]


\[\therefore F(z) = \exp[-\frac{(\mu+\sigma^2z)^2- \mu^2}{2\sigma^2}][1 - \Phi(\frac{-\mu - \sigma^2z}{\sigma})] \quad \forall z \in \mathbb{C}.\]
