---
title: "Tarea 15. Pregunta 19.8."
---

### Suppose that $\Omega = [-1,1]$, $\mathscr{F} = \mathscr{B}(\mathbb{R})$, $\mathbb{P} = \frac{\lambda}{2}$, where $\lambda$ is the Lebesgue measurable in $[-1,1]$. If $X, X_i: \Omega \to \mathbb{R}$, $i = 1,2,3$ are defined as $X(\omega) = \omega$, $X_1(\omega) = |\omega|$, $X_2(\omega) = 2\omega^3$, $X_3(\omega) = \omega^2$. Give the explicit form of 


----------------------------------------------------------------------
(1) $\mathbb{E}[X|X_i] \quad i = 1,2,3.$

Respuesta corta:
\[\begin{split}
\mathbb{E}[X|X_1] &\overset{c.s.}{=} 0\\\\
\mathbb{E}[X|X_2] &\overset{c.s.}{=} X\\\\
\mathbb{E}[X|X_3] &\overset{c.s.}{=} 0\\\\
\end{split}\]

(1.1) $\mathbb{E}[X|X_1]$.

Sabemos que $\sigma(X_1) = \{A \subseteq \Omega: X_1^{-1}(B) = A, B \in \mathscr{B}\}$. Ahora $0<a<b<1$ entonces
\[X_1^{-1}([a,b]) = [-b,-a] \cup [a,b].\]
Es decir, $\sigma(X_1)$ es generada por la unión de intervalos simertricos (uno respecto del otro). Por lo que si $D \in \sigma(X_1)$ entonces:

\[\int_D \mathbb{E}[X|X_1]d\mathbb{P} = \int_D X d \mathbb{P} = \int_{-b}^{-a}\omega d\mathbb{P} + \int_{a}^{b}\omega d\mathbb{P} = 0\]

Por lo tanto
\[\int_D \mathbb{E}[X|X_1] d \mathbb{P} = 0 \quad \forall D \in \sigma(X_1)\]

Como $\int_D \mathbb{E}[X|X_1] d \mathbb{P} = 0$ para todos los elementos de la $\sigma-$álgebra entonces\[\mathbb{E}[X|X_1] \overset{c.s.}{=} 0.\]

(1.2) $\mathbb{E}[X|X_2]$.

Ya que $X_2 = 2\omega^3$ es una biyección de $X = \omega$ entonces $\sigma(X) = \sigma(X_2)$, solo observe que:
\[X_2^{-1}([a,b]) = [(\frac{a}{2})^{\frac{1}{3}},(\frac{b}{2})^{\frac{1}{3}}] = X^{-1}[(\frac{a}{2})^{\frac{1}{3}},(\frac{b}{2})^{\frac{1}{3}}]\]

Así que $X$ es $X_2$-medible. Por lo que
\[\mathbb{E}[X|X_2] =X\]

(1.3) $\mathbb{E}[X|X_3]$.

EL argumento es muy similar a los anteriores, observese que 
\[X_3^{-1}([a,b]) = [-\sqrt{b},-\sqrt{a}] \cup [\sqrt{a},\sqrt{b}]\]
Sea $D \in \sigma(X_3)$ entonces
\[\int_D \mathbb{E}[X|X_3]d\mathbb{P} = \int_DXd\mathbb{P} = \int_{-\sqrt{b}}^{- \sqrt{a}}Xd\mathbb{P} + \int_{\sqrt{a}}^{\sqrt{b}}Xd\mathbb{P} = 0 \quad (\mbox{Simetría})\]
Por lo tanto, 
\[\mathbb{E}[X|X_3]  \overset{c.s.}{=} 0\]


----------------------------------------------------------------------
(2) $\mathbb{E}[X_i|X] \quad i = 1,2,3.$

Respuesta:

Como $X_1$, $X_2$ y $X_3$ son transformaciones medibles de $X$ es claro que \[\sigma(X_1),\sigma(X_2), \sigma(X_3) \subseteq \sigma(X)\]
Por lo que:

\[\begin{split}
\mathbb{E}[X_1|X] &\overset{c.s.}{=} X_1\\\\
\mathbb{E}[X_2|X] &\overset{c.s.}{=} X_2\\\\
\mathbb{E}[X_3|X] &\overset{c.s.}{=} X_3\\\\
\end{split}\]

----------------------------------------------------------------------
(3) $\mathbb{P}(X>0|X_1) \quad i = 1,2,3.$

Sabemos que \[\mathbb{P}(X>0|X_1) = \mathbb{E}(X>0|X_1)\]

Entonces el problema consiste en proponer una $f(X_1) = \mathbb{E}(X>0|X_1)$ tal que $\int_D f(X_1)d\mathbb{P} = \int_D 1_{X>0}d\mathbb{P} \quad \forall D \in \sigma(X_1)$.

Ahora calcularemos $\int_D 1_{X>0} d\mathbb{P}$ con $\mathbb{P} = \frac{\lambda}{2}$.

\[\begin{split}
\int_D 1_{X>0}d\mathbb{P}  &= \int_D 1_{(\omega>0)}d\mathbb{P}\\\\
&= \int_D 1_{(\omega>0)}\frac{d\lambda}{2}\\\\
&= \frac{1}{2}\frac{\lambda(D)}{2} \quad (\mbox{Solo tomamos la parte positiva})\\\\
&= \frac{1}{4}\lambda(D).
\end{split}\]

Por lo que se nos ocurre proponer \[f(X_1) = \frac{1}{2}.\]

\[\int_D \frac{1}{2}d\mathbb{P} = \int_D \frac{1}{2} \frac{d\lambda}{2} = \frac{1}{4}\int_Dd\lambda = \frac{1}{4}\lambda(D)\]

Así, como $D$ fue arbitrario
\[f(X_1) \overset{c.s.}{=} \frac{1}{2}\]

Es decir
\[\mathbb{P}(X>0|X_1) \overset{c.s.}{=} \frac{1}{2}\]