---
title: "Tarea 15. Pregunta 19.6."
---

### $(\Omega^{'},\mathscr{F}^{'})$ be another measurable space and Y a measurable function $Y:(\Omega, \mathscr{F}) \to (\Omega^{'}, \mathscr{F}^{'})$. If $\mbox{Im } Y = \{y_1, y_2, \dots, y_n\} \subset \Omega^{'}$ with $\mathbb{P}(Y = y_i) > 0$, $i = 1, 2, \dots, n$ then we have a measurable partition of $\Omega$ given by $\{B_i = (Y = y_i): i =1, 2, \dots, n\}$: If $\mathscr{A} = \sigma(Y)$ find $\mathbb{E}[X|\sigma(Y)]$ and $\mathbb{E}[X|Y = y_i]$, $i = 1, 2, \dots, n$.

---
Demostraci贸n:

Por la pregunta 19.3 sabemos que 

\[\mathbb{E}[X|A] = \frac{1}{\mathbb{P}(A)}\int_{A} X d\mathbb{P} \quad \forall A \in \mathscr{A}\]

En particular $A = (Y = y_i)$

\[\mathbb{E}[X|Y=y_i] = \frac{1}{\mathbb{P}(Y=y_i)}\int_{(Y=y_i)} X d\mathbb{P}\]

Ahora proponemos a la v.a. $\sum_{i=1}^n\mathbb{E}[X|Y=y_i]1_{Y=y_i}$ como expresi贸n candidata para $\mathbb{E}[X|Y]$.

\[\mbox{PD.} \quad \int_A\sum_{i=1}^n\mathbb{E}[X|Y=y_i]1_{Y=y_i}d\mathbb{P} = \int_AXd\mathbb{P} \quad (\forall A \in \mathscr{A})\]

Tomemos un evento $A \in \mathscr{A}$.

\[\begin{split}
\int_A\sum_{i=1}^n\mathbb{E}[X|Y=y_i]1_{Y=y_i}d\mathbb{P} &= \sum_{i=1}^n\int_A\mathbb{E}[X|Y=y_i]1_{Y=y_i}d\mathbb{P}\\\\
&= \sum_{i=1}^n\int_{A\cap B_i}\mathbb{E}[X|Y=y_i]1_{Y=y_i}d\mathbb{P} \quad (\mbox{Def. } B_i)\\\\
&= \sum_{i=1}^n\int_{A\cap B_i}\mathbb{E}[X|Y=y_i]d\mathbb{P}\quad (\mbox{Simplificaci贸n})\\\\
&= \sum_{i=1}^n\int_{A\cap B_i}Xd\mathbb{P} \quad (\mbox{Def.})\\\\
&= \int_{A}Xd\mathbb{P} \quad (B_i \mbox{ son una partici贸n})
\end{split}\]

Por lo tanto
\[\mathbb{E}[X|Y] \overset{c.s.}{=} \sum_{i=1}^n\mathbb{E}[X|Y=y_i]1_{Y=y_i}\]
