---
title: "Tarea 15. Pregunta 19.1."
---

### Let $B \in \mathscr{F}$ be such that $\mathbb{P}(B) > 0$. Define $Q^B: \mathscr{F} \to [0,1]$ as $Q^B(A) := \frac{\mathbb{P}(A \cap B)}{\mathbb{P}(B)}, \quad A \in \mathscr{F}$.

Show that $Q^B$ is a probability measure in $\mathscr{F}$ usually denoted by $\mathbb{P}(\cdot|B)$ and it is called the conditional probability given $B \in \mathscr{F}$ (this is the elementary form of conditional expectation studied in the basic probability courses).

Demostración:

Sea $\mathbb{Q}^B: \mathscr{A} \to [0,1]$ definida como en el inciso.

PD. $\mathbb{Q}^B$ es una medida de probabilidad.

1. PD.$\mathbb{Q}^B(A) \geq 0$.

Sea $A \in \mathscr{A}$.

\[\mathbb{Q}^B(A) = \frac{\mathbb{P}(A \cap B)}{\mathbb{P}(B)} \geq 0 \implies \mathbb{Q}^B(A) \geq 0.\]

\[\therefore \forall  A \in \mathscr{A} \quad \mathbb{Q}^B(A) \geq 0.\]

2. PD. $\mathbb{Q}^B(\Omega) = 1$.

\[\mathbb{Q}^B(\Omega) = \frac{\mathbb{P}(\Omega \cap B)}{\mathbb{P}(B)} = \frac{\mathbb{P}(B)}{\mathbb{P}(B)} = 1.\]

\[\therefore \mathbb{Q}^B(\Omega) = 1\]

3. PD. $\mathbb{Q}^B(\cup_{n \in \mathbb{N}} A_n) = \sum_{n \in \mathbb{N}} \mathbb{Q}^B(A_n) \quad \mbox{Si} \quad A_i \cap A_j = \emptyset \quad i \neq j.$

Sea $\{A_n\}_{n \in \mathbb{N}}$ una familia de eventos disjuntos a pares.

\[\begin{align*}
\mathbb{Q}^B(\cup_{n \in \mathbb{N}} A_n) &= \frac{\mathbb{P}[(\cup_{n \in \mathbb{N}} A_n) \cap B]}{\mathbb{P}(B)} && (\mbox{Def.} \mathbb{Q}^B)\\\\
&= \frac{\mathbb{P}[\cup_{n \in \mathbb{N}} (A_n \cap B)]}{\mathbb{P}(B)} &&(\mbox{Prop. } \cap)\\\\
&= \frac{\sum_{n \in \mathbb{N}}\mathbb{P}(A_n\cap B)}{\mathbb{P}(B)} && ((A_i\cap B) \cap (A_j \cap B) = \emptyset \quad i \neq j)\\\\
&= \sum_{n \in \mathbb{N}} \frac{\mathbb{P}(A_n\cap B)}{\mathbb{P}(B)}\\\\
&= \sum_{n \in \mathbb{N}} \mathbb{Q}^B(A_n).
\end{align*}\]

Por lo tanto
\[\mathbb{Q}^B(\cup_{n \in \mathbb{N}} A_n) = \sum_{n \in \mathbb{N}} \mathbb{Q}^B(A_n).\]

Por lo que se concluye que $\mathbb{Q}^B$ es una medida de probabilidad.

