---
title: "Tarea 4. Pregunta 7.2"
subtitle: Sea $(\Omega,\mathscr{A},\mathbb{P})$ un espacio de probabilidad y $X$ una v.a. definida en $\Omega$. Si $X \geq 0$ y $\mathbb{E}(X) = 0$ entonces $X$ es cero salvo en un conjunto de medida cero. Si se quita la hipótesis $X \geq 0$ es cierto el resultado?
---
Demostración:

Observemos que 

\begin{align*}
\mathbb{E}(X) &= \int_{\Omega} Xd\mathbb{P}\\\\
&= \int_{\{X = 0\} \cup \{X>0\}} Xd\mathbb{P}\\\\
&= \int_{\{X = 0\}} Xd\mathbb{P} + \int_{\{X>0\}} Xd\mathbb{P}\\\\
&= \int_{\{X>0\}} Xd\mathbb{P}
\end{align*}

Lo anterior nos motiva a definir el evento $A_x := X \geq x$ con $x>0$. De esta manera podemos construir una v.a. que acote inferiormente a $X$.

\[X \geq x 1_{A_x}\]

Puesto que si $1_{A_x} = 1$ entonces $X \geq x$ y se cumple la desigualdad. En el otro caso $1_{A_x} = 0$ por lo que se cumpliria la desigualdad por la hipótesis de no negatividad de $X$.

Y si tomamos esperanzas:

\[\mathbb{E}(X) \geq \mathbb{E}(x 1_{A_x})\]

Y recordando que la esperanza de una indicadora es la probabilidad del evento tenemos que:

\[\mathbb{E}(X) \geq x\mathbb{P}(A_x) \quad \forall x>0.\]

Así, cuando $x = \frac{1}{n}$ con $n \in \mathbb{N}$ tenemos que:

\[\frac{1}{n}\mathbb{P}(A_{\frac{1}{n}}) \leq \int_{A_{\frac{1}{n}}} Xd\mathbb{P} \leq \int_{X > 0} Xd\mathbb{P} = 0\]

Por lo que 

\[\mathbb{P}(A_{\frac{1}{n}}) = 0 \quad \forall n \in \mathbb{N}\]

Y observando que

\[(X>0) = \cup_n (X \geq \frac{1}{n}) = \cup_n A_{\frac{1}{n}} \]

Se sigue que

\[\mathbb{P}(X>0) \leq \sum_{n \in \mathbb{N}}\mathbb{P}(A_{\frac{1}{n}}) = 0\]

Por lo tanto:

\[\mathbb{P}(X>0) = 0 \quad \therefore \mathbb{P}(X = 0) = 1\].


Si se quita la hipótesis de que $X \geq 0$ el resultado no es verdadero. Contraejemplo: Normal(0,1).

