---
title: "Parcial 3. Pregunta 4."
---
### Austria Max
### Si $\sum_{n} \mathbb{Var}(X_n) < \infty$ entonces $X_n \overset{c.s.}{\to} X$.



Demostración:

Antes de ver la demostración voy a decir que el enunciado es cierto si $\mathbb{E}[X_n]$ es constante, en otro caso voy a dar un constrajemplo.


Caso 1: $\mathbb{E}[X_n]$ es constante.


Sabemos que 

\[\begin{align*}
\sum_{n} \mathbb{Var}(X_n) < \infty &\implies \mathbb{Var}(X_n)<\infty \quad \forall n\in \mathbb{N}\\\\
&\implies \mathbb{E}(X_n)<\infty \quad \forall n\in \mathbb{N}
\end{align*}\]

Construyendo
\[Y_n = X_n - \mathbb{E}(X_n) \quad \mbox{para }n\geq N_0\]
Obtenemos:


(1)
\[\begin{align*}
\mathbb{E}(Y_n) &= \mathbb{E}[X_n - \mathbb{E}(X_n)]\\\\ 
&= \mathbb{E}(X_n) - \mathbb{E}(X_n)\\\\
&= 0\\\\
&\therefore \mathbb{E}(Y_n) = 0.
\end{align*}\]

(2)
\[\begin{align*}
\mathbb{Var}(Y_n) &= \mathbb{Var}[X_n - \mathbb{E}(X_n)]\\\\ 
&= \mathbb{Var}(X_n)\\\\
\end{align*}\]

(3)
\[\begin{align*}
\mathbb{Var}(Y_n) &= \mathbb{E}(Y_n^2) - \mathbb{E}(Y_n)^2\\\\ 
&= \mathbb{E}(Y_n^2)\\\\
&\therefore \sum_n\mathbb{E}(Y_n^2) < \infty.
\end{align*}\]

Así, tenemos una variable aletaria no negativa $Y_n^2$ cuya serie de medias converge $\sum_n \mathbb{E}(Y_n^2) < \infty$. Por lo que sabemos que:

\[Y_n^2 \overset{c.s.}{\to} 0\]

De lo que se desprende que:

\[\begin{align*}
Y_n^2 \overset{c.s.}{\to} 0 &\implies Y_n \overset{c.s.}{\to} 0\\\\
&\implies X_n \overset{c.s.}{\to} \mathbb{E}[X_n]\\\\
&\therefore X_n \overset{c.s.}{\to} c \quad \mbox{con} \quad c = \mathbb{E}(X_n).
\end{align*}\]

Caso 2:  $\mathbb{E}[X_n]$ divergente.

En este caso daremos un constrajemplo.

\[   
X_n = 
     \begin{cases}
       A_n \sim Unif(-\frac{1}{2^n},\frac{1}{2^n}) &\quad\text{si }n \text{ es par}\\
       1 + A_n &\quad\text{en otro caso.} \\ 
     \end{cases}
\]

Entonces 
(1)
\[\begin{align*}
\sum_n\mathbb{Var}(X_n) &= \sum_n \frac{[(\mathbb{E}[X_n]+\frac{1}{2^n}) - (\mathbb{E}[X_n]-\frac{1}{2^n})]^2}{12}\\\\
&= \sum_n \frac{(\frac{1}{2^{n-1}})^2}{12}<\infty.
\end{align*}\]

(2)
\[X_n \overset{c.s.}{\to}  
     \begin{cases}
         0  &\quad\text{si }n \text{ es par}\\
        1 &\quad\text{en otro caso.} \\ 
\end{cases}\]